# Generated by Django 5.0.4 on 2024-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
